version: '3.8'

services:
  stats-server:
    build: ./stats/stats-server
    container_name: container_stats
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345

  stats-db:
    image: postgres:16.3
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 10s
      retries: 10

  ewm-service:
    build: ./main-service
    container_name: ewm-main-server
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ewm-db:5432/mainservice
      SPRING_DATASOURCE_USERNAME: dbuser
      SPRING_DATASOURCE_PASSWORD: 12345
      STATS_SERVER_URL: http://stats-server:9090

  ewm-db:
    image: postgres:16.3
    container_name: ewm_db
    ports:
      - "6542:5432"
    environment:
      POSTGRES_DB: mainservice
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: 12345
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d $POSTGRES_DB -U $POSTGRES_USER" ]
      interval: 10s
      timeout: 10s
      retries: 10